/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import model.Database;
import model.StudyClub;

/**
 *
 * @author adindasalsabillanaura
 */
public class CreateData extends javax.swing.JFrame {

    /**
     * Creates new form CreateData
     */
    public CreateData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namascField = new javax.swing.JTextField();
        jadwalscField = new javax.swing.JTextField();
        deskripsiField = new javax.swing.JTextField();
        kapasitaspesertaField = new javax.swing.JTextField();
        penanggungjawabField = new javax.swing.JTextField();
        jenisscBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namascField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        namascField.setBorder(null);
        namascField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namascFieldActionPerformed(evt);
            }
        });
        getContentPane().add(namascField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 470, 40));

        jadwalscField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jadwalscField.setBorder(null);
        jadwalscField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalscFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jadwalscField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 480, 40));

        deskripsiField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        deskripsiField.setBorder(null);
        deskripsiField.setPreferredSize(new java.awt.Dimension(65, 23));
        deskripsiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deskripsiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 480, 40));

        kapasitaspesertaField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        kapasitaspesertaField.setBorder(null);
        kapasitaspesertaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapasitaspesertaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(kapasitaspesertaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 480, 40));

        penanggungjawabField.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        penanggungjawabField.setBorder(null);
        penanggungjawabField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penanggungjawabFieldActionPerformed(evt);
            }
        });
        getContentPane().add(penanggungjawabField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 520, 50));

        jenisscBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jenisscBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akademik", "Non-Akademik" }));
        getContentPane().add(jenisscBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Create Data.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        createButton.setText("jButton1");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 180, 60));

        homeButton.setText("jButton1");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namascFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namascFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namascFieldActionPerformed

    private void deskripsiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiFieldActionPerformed

    private void jadwalscFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalscFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalscFieldActionPerformed

    private void kapasitaspesertaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapasitaspesertaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapasitaspesertaFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        try {
            String namaSC = namascField.getText();
            String deskripsi = deskripsiField.getText();
            String jadwalSC = jadwalscField.getText();
            String kapasitasPeserta = kapasitaspesertaField.getText();
            String namaPenanggungJawab = penanggungjawabField.getText();
            String jenisSC = jenisscBox.getSelectedItem().toString();
            int kapasitas = Integer.parseInt(kapasitaspesertaField.getText());
            // Validasi input
            if (namaSC.isEmpty() || deskripsi.isEmpty() || jadwalSC.isEmpty() || kapasitasPeserta.isEmpty() || namaPenanggungJawab.isEmpty() || kapasitas == 0) {
                JOptionPane.showMessageDialog(this, "Tolong isi semua field!");
                return;
            } else {
                StudyClub studyClub = new StudyClub(namaSC, kapasitas, jadwalSC, deskripsi, namaPenanggungJawab, jenisSC); 
                studyClub.createStudyClub();
                JOptionPane.showMessageDialog(this, "Study Club berhasil dibuat dan disimpan di database!");
            }

            clearFields();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_createButtonActionPerformed
// Fungsi untuk membersihkan field input
    private void clearFields() {
        namascField.setText("");
        deskripsiField.setText("");
        jadwalscField.setText("");
        kapasitaspesertaField.setText("");
        penanggungjawabField.setText("");
        jenisscBox.setSelectedIndex(0);
    }

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // Pindah ke menu admin
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        menuAdmin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void penanggungjawabFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penanggungjawabFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penanggungjawabFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Pastikan koneksi database terhubung
            Database.connect();
            new CreateData().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextField deskripsiField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jadwalscField;
    private javax.swing.JComboBox<String> jenisscBox;
    private javax.swing.JTextField kapasitaspesertaField;
    private javax.swing.JTextField namascField;
    private javax.swing.JTextField penanggungjawabField;
    // End of variables declaration//GEN-END:variables
}
