/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.Database;
import model.StudyClub;

/**
 *
 * @author adindasalsabillanaura
 */
public class DeleteData extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    /**
     * Creates new form DeleteData
     */
    public DeleteData() {
        Database.connect();
        initComponents();
        loadStudyClubData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jadwalScjScrollPane = new javax.swing.JScrollPane();
        tabelSC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelSC.setBackground(new java.awt.Color(153, 204, 255));
        tabelSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "kapasitas", "deskripsi", "jadwal", "penanggung jawab", "jenis"
            }
        ));
        jadwalScjScrollPane.setViewportView(tabelSC);

        getContentPane().add(jadwalScjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 650, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete Data.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        homeButton.setText("jButton1");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 150, 60));

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 150, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadStudyClubData() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club");
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            int selectedRow = tabelSC.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabelSC.getModel();
                int id = Integer.parseInt(tabelSC.getValueAt(selectedRow, 0).toString());
                StudyClub studyClub = new StudyClub(id);
                studyClub.deleteStudyClub();
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jadwalScjScrollPane;
    private javax.swing.JTable tabelSC;
    // End of variables declaration//GEN-END:variables
}
