/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import model.Database;

/**
 *
 * @author adindasalsabillanaura
 */
public class JadwalSC extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    /**
     * Creates new form JadwalSC
     */
    public JadwalSC() {
        initComponents();
        Database.connect();
        loadStudyClubData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        sortdescendingButton = new javax.swing.JButton();
        sortascendingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setBorder(null);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 320, 40));

        tabelSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nama", "jadwal"
            }
        ));
        jScrollPane1.setViewportView(tabelSC);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 560, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jadwalsc.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        searchButton.setText("jButton1");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, 60));

        homeButton.setText("jButton1");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 60));

        sortdescendingButton.setText("jButton1");
        sortdescendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortdescendingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortdescendingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 253, 70, 60));

        sortascendingButton.setText("jButton2");
        sortascendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortascendingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortascendingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        MenuMahasiswa menuMahasiswa = new MenuMahasiswa();
        menuMahasiswa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void sortascendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortascendingButtonActionPerformed
        loadStudyClubDataAscending();
    }//GEN-LAST:event_sortascendingButtonActionPerformed

    private void sortdescendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortdescendingButtonActionPerformed
        loadStudyClubDataDescending();
    }//GEN-LAST:event_sortdescendingButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        loadStudyClubDataSearching();
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void loadStudyClubDataAscending() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jadwal");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club ORDER BY nama_sc ASC");
            while (resultSet.next()) {
                String namaSC = resultSet.getString("nama_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                
                tableModel.addRow(new Object[]{
                    namaSC,
                    jadwalSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubDataDescending() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jadwal");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club ORDER BY nama_sc DESC");
            while (resultSet.next()) {       
                String namaSC = resultSet.getString("nama_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                
                tableModel.addRow(new Object[]{
                    namaSC,
                    jadwalSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubDataSearching() {
        tableModel = new DefaultTableModel();
        tableModel.setRowCount(0);
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jadwal");
        try {
            String nama = searchField.getText();
            System.out.println(nama);
            String query = "SELECT * FROM study_club WHERE nama_sc = ?";
            PreparedStatement preparedStatement = Database.connection.prepareStatement(query);
            preparedStatement.setString(1, nama);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {                
                String namaSC = resultSet.getString("nama_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                
                tableModel.addRow(new Object[]{
                    namaSC,
                    jadwalSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubData() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setRowCount(0);
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jadwal");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club");
            while (resultSet.next()) {                
                String namaSC = resultSet.getString("nama_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                
                tableModel.addRow(new Object[]{
                    namaSC,
                    jadwalSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JadwalSC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortascendingButton;
    private javax.swing.JButton sortdescendingButton;
    private javax.swing.JTable tabelSC;
    // End of variables declaration//GEN-END:variables
}
