/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Database;

/**
 *
 * @author adindasalsabillanaura
 */
public class ReadData extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    /**
     * Creates new form ReadData
     */
    public ReadData() {
        Database.connect();
        initComponents();
        loadStudyClubData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jadwalScjScrollPane = new javax.swing.JScrollPane();
        tabelSC = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        sortdescendingButton = new javax.swing.JButton();
        sortascendingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelSC.setBackground(new java.awt.Color(153, 204, 255));
        tabelSC.setForeground(new java.awt.Color(0, 0, 0));
        tabelSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "kapasitas", "deskripsi", "jadwal", "penanggung jawab", "jenis"
            }
        ));
        jadwalScjScrollPane.setViewportView(tabelSC);

        getContentPane().add(jadwalScjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 1030, 380));

        searchField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        searchField.setBorder(null);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ReadData.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        searchButton.setText("jButton1");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 243, 80, 60));

        homeButton.setText("jButton1");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, 160, 60));

        sortdescendingButton.setText("jButton1");
        sortdescendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortdescendingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortdescendingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 243, 50, 60));

        sortascendingButton.setText("jButton1");
        sortascendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortascendingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortascendingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 240, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadStudyClubData() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club");
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubDataAscending() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club ORDER BY nama_sc ASC");
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubDataDescending() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club ORDER BY nama_sc DESC");
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void loadStudyClubDataSearching() {
        tableModel = new DefaultTableModel();
        tableModel.setRowCount(0);
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            String nama = searchField.getText();
            System.out.println(nama);
            String query = "SELECT * FROM study_club WHERE nama_sc = ?";
            PreparedStatement preparedStatement = Database.connection.prepareStatement(query);
            preparedStatement.setString(1, nama);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                tabelSC.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            if (searchField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ID tidak boleh kosong");
            } else {
                loadStudyClubDataSearching();
            }
        } catch (Exception e) {
        }
        loadStudyClubDataSearching();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void sortascendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortascendingButtonActionPerformed
        loadStudyClubDataAscending();
    }//GEN-LAST:event_sortascendingButtonActionPerformed

    private void sortdescendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortdescendingButtonActionPerformed
        loadStudyClubDataDescending();
    }//GEN-LAST:event_sortdescendingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jadwalScjScrollPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortascendingButton;
    private javax.swing.JButton sortdescendingButton;
    private javax.swing.JTable tabelSC;
    // End of variables declaration//GEN-END:variables
}
