/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Database;
import model.StudyClub;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author adindasalsabillanaura
 */
public class UpdateData extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    int selectedRowId;
    /**
     * Creates new form UpdateData
     */
    public UpdateData() {
        initComponents();
        loadStudyClubData(); // Panggil method untuk load data saat form pertama kali dibuka
        
        
        updateTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = updateTable1.getSelectedRow();
                if (row != -1) {
                    selectedRowId = Integer.parseInt(updateTable1.getValueAt(row, 0).toString()); // Ambil ID
                    namascField.setText(updateTable1.getValueAt(row, 1).toString());
                    kapasitaspesertaField.setText(updateTable1.getValueAt(row, 2).toString());
                    deskripsiField.setText(updateTable1.getValueAt(row, 3).toString());
                    jadwalscField.setText(updateTable1.getValueAt(row, 4).toString());
                    penanggungjawabField.setText(updateTable1.getValueAt(row, 5).toString());
                    jenisBox.setSelectedItem(updateTable1.getValueAt(row, 6).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        updateTable1 = new javax.swing.JTable();
        namascField = new javax.swing.JTextField();
        deskripsiField = new javax.swing.JTextField();
        jadwalscField = new javax.swing.JTextField();
        kapasitaspesertaField = new javax.swing.JTextField();
        penanggungjawabField = new javax.swing.JTextField();
        jenisBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateTable1.setBackground(new java.awt.Color(153, 204, 255));
        updateTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Study Club", "Deskripsi", "Jadwal", "Kapasitas", "Jenis Study Club"
            }
        ));
        jScrollPane1.setViewportView(updateTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 650, 330));

        namascField.setBorder(null);
        namascField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namascFieldActionPerformed(evt);
            }
        });
        getContentPane().add(namascField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 380, 30));

        deskripsiField.setBorder(null);
        deskripsiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deskripsiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 380, 40));

        jadwalscField.setBorder(null);
        jadwalscField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalscFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jadwalscField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 380, 30));

        kapasitaspesertaField.setBorder(null);
        kapasitaspesertaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapasitaspesertaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(kapasitaspesertaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 392, 380, 30));

        penanggungjawabField.setBorder(null);
        penanggungjawabField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penanggungjawabFieldActionPerformed(evt);
            }
        });
        getContentPane().add(penanggungjawabField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 462, 380, 30));

        jenisBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jenisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akademik", "Non Akademik" }));
        jenisBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jenisBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 502, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Update Data.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        updateButton.setText("jButton1");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 510, 130, 50));

        homeButton.setText("jButton1");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadStudyClubData() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Kapasitas");
        tableModel.addColumn("Deskripsi");
        tableModel.addColumn("Jadwal");
        tableModel.addColumn("Penanggung Jawab");
        tableModel.addColumn("jenis");
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM study_club");
            while (resultSet.next()) {                
                int idSC = resultSet.getInt("id_sc");
                String namaSC = resultSet.getString("nama_sc");
                String kapasitasSC = resultSet.getString("kapasitas_sc");
                String deskripsiSC = resultSet.getString("deskripsi_sc");
                String jadwalSC = resultSet.getString("jadwal_sc");
                String pjSC = resultSet.getString("penanggungjawab_sc");
                String jenisSC = resultSet.getString("jenis_sc");
                
                tableModel.addRow(new Object[]{
                    idSC,
                    namaSC,
                    kapasitasSC,
                    deskripsiSC,
                    jadwalSC,
                    pjSC,
                    jenisSC});
                updateTable1.setModel(tableModel);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }    
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int selectedRow = updateTable1.getSelectedRow();
        if (selectedRow >= 0) {
            int id = Integer.parseInt(updateTable1.getValueAt(selectedRow, 0).toString());
            String namaSC = namascField.getText();
            String deskripsiSC = deskripsiField.getText();
            String jadwalSC = jadwalscField.getText();
            String kapasitasSC = kapasitaspesertaField.getText();
            String pjSC = penanggungjawabField.getText();
            String jenisSC = jenisBox.getSelectedItem().toString();

            try {
                String query = "UPDATE study_club SET nama_sc = '" + namaSC + "', deskripsi_sc = '" + deskripsiSC + "', jadwal_sc = '" + jadwalSC + "', kapasitas_sc = '" + kapasitasSC + "', penanggungjawab_sc = '" + pjSC + "', jenis_sc = '" + jenisSC + "' WHERE id_sc = " + id;
                Statement statement = Database.connection.createStatement();
                statement.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                loadStudyClubData(); // Reload tabel setelah update
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mohon pilih baris kalom untuk diperbarui!");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void namascFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namascFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namascFieldActionPerformed

    private void deskripsiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiFieldActionPerformed

    private void jadwalscFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalscFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalscFieldActionPerformed

    private void kapasitaspesertaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapasitaspesertaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapasitaspesertaFieldActionPerformed

    private void penanggungjawabFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penanggungjawabFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penanggungjawabFieldActionPerformed

    private void jenisBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deskripsiField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jadwalscField;
    private javax.swing.JComboBox<String> jenisBox;
    private javax.swing.JTextField kapasitaspesertaField;
    private javax.swing.JTextField namascField;
    private javax.swing.JTextField penanggungjawabField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable updateTable1;
    // End of variables declaration//GEN-END:variables
}
